### PR TITLE
rip out the require 'locale'

### PR DESCRIPTION
**Pull request by telyn**
Locale is apparently not so useful in modern rubys so I've removed it to get my docker setup working. This doesn't completely remove all reference to the Locale class, just removes the require (since the only reference to Locale checks it exists first)

### CODE REVIEW

**Comment by patch0** [comment]
If you're ripping out that line (and I'd just delete), you should probably remove stuff around Line 159 too.

**Comment by telyn** [comment]
I just discovered that from_charset was completely unused anyway 😆

**Comment by patch0** [comment]
Just needs a changelog entry :)

**Comment by telyn** [comment]
Is it a new version or just an extra line on the changelog?

**Comment by patch0** [comment]
Looks like just an extra line

**Comment by telyn** [comment]
Tests still pass \m/

**Pull request merged**
